services:
  postgres:
    image: postgis/postgis:14-3.4
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  transiter:
    image: jamespfennell/transiter:latest
    environment:
      - POSTGRES_CONNECTION_STRING=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    restart: always
    entrypoint: >
      /bin/sh -c "
        transiter server --log-level info --postgres-connection-string \"$$POSTGRES_CONNECTION_STRING\" &
        sleep 10 &&
        transiter install us-ny-subway &&
        wait
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - TRANSITER_URL=http://transiter:8080
    depends_on:
      - postgres
      - transiter

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    environment:
      - VITE_API_URL=/api

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - frontend
      - backend
      - transiter

volumes:
  postgres-data:
  caddy-data:
  caddy-config:

networks:
  default:
    name: app-network

